Adding blog post on Bean Validation 2.0 progress
beanvalidation/beanvalidation.org pull request #47
Opened 2017-01-19 14:41 UTC by gunnarmorling

2017-01-19 15:01 UTC, gsmet reviewed
Looks good. Added a couple of comments inline.

Wondering if we shouldn't talk about the remaining challenges of the container thing and add a link to the open questions.

2017-01-19 15:01 UTC, gsmet commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +It has been a few months since we've kicked of the work on Bean Validation 2.0 (JSR 380).
kicked of**f**?

2017-01-19 15:01 UTC, gsmet commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +Types such as `Instant`, `LocalDate` or `ZonedDateTime` are supported by the `@Past` and `@Future` constraints now ([BVAL-496](https://hibernate.atlassian.net/browse/BVAL-496)):
I think it would be better to have `now` after `are`: are now supported

2017-01-19 15:01 UTC, gsmet commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +`@Past` and `@Future` also have a new attribute `orPresent()` now:
I think 'now also have' reads better.

2017-01-19 15:01 UTC, gsmet commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +    Validator validator = Validation.byDefaultProvider()
We don't have syntax highlighting with the triple backticks?

2017-01-19 15:01 UTC, gsmet commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +Check out the [latest spec draft](http://beanvalidation.org/latest-draft/spec/#appendix-valueextraction-wrappedelements) to learn more about how this is handled.
Hmmm, the spec is currently not in line with the API and the RI.

2017-01-19 15:01 UTC, gsmet commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +This should get the discussed changes into the hands of more people out there and will let us improve and hone the features added so far.
hone?

2017-01-19 15:01 UTC, gsmet commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +Could there be a better representation of Bean Validation thank Duke validating a bean?
s/thank/than/

2017-01-19 15:29 UTC, gunnarmorling commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +It has been a few months since we've kicked of the work on Bean Validation 2.0 (JSR 380).
Done.

2017-01-19 15:29 UTC, gunnarmorling commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +Types such as `Instant`, `LocalDate` or `ZonedDateTime` are supported by the `@Past` and `@Future` constraints now ([BVAL-496](https://hibernate.atlassian.net/browse/BVAL-496)):
Done.

2017-01-19 15:29 UTC, gunnarmorling commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +`@Past` and `@Future` also have a new attribute `orPresent()` now:
Done.

2017-01-19 15:29 UTC, gunnarmorling commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +    Validator validator = Validation.byDefaultProvider()
Didn't work for me. Converted it to *.adoc.

2017-01-19 15:30 UTC, gunnarmorling commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +Check out the [latest spec draft](http://beanvalidation.org/latest-draft/spec/#appendix-valueextraction-wrappedelements) to learn more about how this is handled.
That's true. Some update is due.

2017-01-19 15:30 UTC, gunnarmorling commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +This should get the discussed changes into the hands of more people out there and will let us improve and hone the features added so far.
https://www.merriam-webster.com/dictionary/hone

2017-01-19 15:30 UTC, gunnarmorling commented on news/2017-01-19-bean-validation-2-0-progress-report.md
> +Could there be a better representation of Bean Validation thank Duke validating a bean?
Done.

2017-01-19 15:34 UTC, gunnarmorling commented
> Looks good. Added a couple of comments inline.

Thanks for the quick review. Pushed an update for converting to *.adoc and addressing your remarks.

> Wondering if we shouldn't talk about the remaining challenges of the container thing and add a link to the open questions.

I've added the link but didn't dive into details here. I think it's too deep for this post, also it's very long already anyways.

2017-01-19 15:47 UTC, gunnarmorling commented
It's also on staging if you prefer the actual preview: http://staging.beanvalidation.org/news/2017/01/19/bean-validation-2-0-progress-report/

2017-01-19 16:40 UTC, gsmet commented on news/2017-01-19-bean-validation-2-0-progress-report.adoc
> +With the first EG members on board, we didn't loose time and began with the work on the new spec revision.
s/loose/lose/

2017-01-19 16:42 UTC, gsmet commented on news/2017-01-19-bean-validation-2-0-progress-report.adoc
> +Similarly, it's possible to put constraints to the elements of an array:
Maybe "put constraints on" would be better?

2017-01-20 09:19 UTC, emmanuelbernard requested changes

2017-01-20 09:19 UTC, emmanuelbernard commented on news/2017-01-19-bean-validation-2-0-progress-report.adoc
> +== Validation of container elements
This is not a good title for the audience this blog targets. It needs to mention concrete ones: `Collection` and `Optional`
You can mention later that it is generalized.

2017-01-20 09:19 UTC, emmanuelbernard commented on news/2017-01-19-bean-validation-2-0-progress-report.adoc
> +(so far, only values were validated) by using `@Valid` like this:
s/so far/until now/

2017-01-20 09:19 UTC, emmanuelbernard commented on news/2017-01-19-bean-validation-2-0-progress-report.adoc
> +We consider to detect custom extractors using the http://docs.oracle.com/javase/8/docs/api/index.html?java/util/ServiceLoader.html[service loader mechanism],
We are considering (or contemplating)

2017-01-20 09:19 UTC, emmanuelbernard commented on news/2017-01-19-bean-validation-2-0-progress-report.adoc
> +If you have thoughts on any of those, please make sure to let us know, e.g. by commenting below.
If one can run and play with it in the RI, mention it.

2017-01-20 09:19 UTC, emmanuelbernard commented on news/2017-01-19-bean-validation-2-0-progress-report.adoc
> +Once that is done, we feel it is the right time to put out an Alpha1 release of Bean Validation 2.0 and post it for Early Draft Review to the JCP.
Hum really, we are waiting for feedback and another new cycle before pushing it? I'm against that. Pushing it in the JSP is about feedback.

2017-01-20 09:19 UTC, emmanuelbernard commented on news/2017-01-19-bean-validation-2-0-progress-report.adoc
> +The feedback when https://twitter.com/gunnarmorling/status/819631488358563840[sharing the idea] on Twitter was https://twitter.com/dblevins/status/819633752888475648[very encouraging].
You know David has been pushing for it in the first place so that's not surprising

2017-01-20 09:24 UTC, gunnarmorling commented on news/2017-01-19-bean-validation-2-0-progress-report.adoc
> +== Validation of container elements
Ok.

2017-01-20 09:24 UTC, gunnarmorling commented on news/2017-01-19-bean-validation-2-0-progress-report.adoc
> +Once that is done, we feel it is the right time to put out an Alpha1 release of Bean Validation 2.0 and post it for Early Draft Review to the JCP.
Not waiting really, what I had in mind here is to manifest the latest agreements on some of the open questions in the doc. I'll reword.

2017-01-20 09:25 UTC, gunnarmorling commented on news/2017-01-19-bean-validation-2-0-progress-report.adoc
> +The feedback when https://twitter.com/gunnarmorling/status/819631488358563840[sharing the idea] on Twitter was https://twitter.com/dblevins/status/819633752888475648[very encouraging].
Sure, I like the number of favs and retweets, though :)

2017-01-20 13:04 UTC, merged